cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy
  - release

unit_test:
  stage: test
  script:
    - deploy/unit_test.sh

build_app_staging:
  stage: build
  script:
    - deploy/compile_app.sh
    - deploy/build_docker_image.sh
  variables:
    NODE_ENV: "staging"
    DISCOVERY_SERVICE_HOST: "staging-beruni.herokuapp.com"
    DISCOVERY_SERVICE_PORT: "80"
    DISCOVERY_SERVICE_PATH: "/assets/staging.json"
    CUSTOM_ENVIRONMENT: "staging-"

deploy_staging:
  stage: deploy
  script:
    - deploy/push_to_heroku.sh
  variables:
    CUSTOM_ENVIRONMENT: "staging-"

build_app:
  stage: release
  script:
    - deploy/compile_app.sh
    - deploy/build_docker_image.sh
  variables:
    NODE_ENV: "production"
    DISCOVERY_SERVICE_HOST: "beruni.herokuapp.com"
    DISCOVERY_SERVICE_PORT: "80"
    DISCOVERY_SERVICE_PATH: "/assets/production.json"

deploy_staging:
  stage: release
  script:
    - deploy/push_to_heroku.sh


